name: flutter_course
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  #apis  
  dio: ^5.7.0
  http: ^1.2.2

  #maps
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  place_picker_google: ^0.0.14
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  shared_preferences: ^2.3.5
  location: ^7.0.1
  widget_to_marker: ^1.0.6
  flutter_tts: ^4.2.1
  flutter_google_maps_webservices: ^1.1.1

  #animations
  flutter_animate: ^4.5.2

  # RTC communications
  zego_uikit_prebuilt_call: ^4.16.21
  


  #states management
  get: ^4.6.6
  riverpod: ^2.6.1
  provider: ^6.1.2
  flutter_bloc: ^8.1.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

 # formatters
  flutter_lints: ^4.0.0


# The following section is specific to Flutter packages.
flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
