// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package db_gen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    email, phone_number, first_name, last_name, date_of_birth, country_code, status, kyc_level
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, email, phone_number, first_name, last_name, date_of_birth, status, kyc_level, country_code, metadata, created_at, updated_at
`

type CreateCustomerParams struct {
	Email       string         `json:"email"`
	PhoneNumber sql.NullString `json:"phone_number"`
	FirstName   string         `json:"first_name"`
	LastName    string         `json:"last_name"`
	DateOfBirth sql.NullTime   `json:"date_of_birth"`
	CountryCode string         `json:"country_code"`
	Status      CustomerStatus `json:"status"`
	KycLevel    KycTier        `json:"kyc_level"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.Email,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.DateOfBirth,
		arg.CountryCode,
		arg.Status,
		arg.KycLevel,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Status,
		&i.KycLevel,
		&i.CountryCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, email, phone_number, first_name, last_name, date_of_birth, status, kyc_level, country_code, metadata, created_at, updated_at FROM customers
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Status,
		&i.KycLevel,
		&i.CountryCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, email, phone_number, first_name, last_name, date_of_birth, status, kyc_level, country_code, metadata, created_at, updated_at FROM customers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Status,
		&i.KycLevel,
		&i.CountryCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :one
UPDATE customers
SET status = $2
WHERE id = $1
RETURNING id, email, phone_number, first_name, last_name, date_of_birth, status, kyc_level, country_code, metadata, created_at, updated_at
`

type UpdateCustomerStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status CustomerStatus `json:"status"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomerStatus, arg.ID, arg.Status)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.DateOfBirth,
		&i.Status,
		&i.KycLevel,
		&i.CountryCode,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
