// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_gen

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AccountStatus string

const (
	AccountStatusACTIVE AccountStatus = "ACTIVE"
	AccountStatusFROZEN AccountStatus = "FROZEN"
	AccountStatusCLOSED AccountStatus = "CLOSED"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type AccountType string

const (
	AccountTypeSAVINGS  AccountType = "SAVINGS"
	AccountTypeCHECKING AccountType = "CHECKING"
	AccountTypeSYSTEM   AccountType = "SYSTEM"
	AccountTypeSUSPENSE AccountType = "SUSPENSE"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AlertStatus string

const (
	AlertStatusOPEN                  AlertStatus = "OPEN"
	AlertStatusINVESTIGATING         AlertStatus = "INVESTIGATING"
	AlertStatusRESOLVEDFALSEPOSITIVE AlertStatus = "RESOLVED_FALSE_POSITIVE"
	AlertStatusRESOLVEDTRUEPOSITIVE  AlertStatus = "RESOLVED_TRUE_POSITIVE"
)

func (e *AlertStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AlertStatus(s)
	case string:
		*e = AlertStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AlertStatus: %T", src)
	}
	return nil
}

type NullAlertStatus struct {
	AlertStatus AlertStatus `json:"alert_status"`
	Valid       bool        `json:"valid"` // Valid is true if AlertStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAlertStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AlertStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AlertStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAlertStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AlertStatus), nil
}

type BeneficiaryStatus string

const (
	BeneficiaryStatusACTIVE   BeneficiaryStatus = "ACTIVE"
	BeneficiaryStatusINACTIVE BeneficiaryStatus = "INACTIVE"
	BeneficiaryStatusDELETED  BeneficiaryStatus = "DELETED"
)

func (e *BeneficiaryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BeneficiaryStatus(s)
	case string:
		*e = BeneficiaryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BeneficiaryStatus: %T", src)
	}
	return nil
}

type NullBeneficiaryStatus struct {
	BeneficiaryStatus BeneficiaryStatus `json:"beneficiary_status"`
	Valid             bool              `json:"valid"` // Valid is true if BeneficiaryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBeneficiaryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BeneficiaryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BeneficiaryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBeneficiaryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BeneficiaryStatus), nil
}

type CardStatus string

const (
	CardStatusPENDING   CardStatus = "PENDING"
	CardStatusACTIVE    CardStatus = "ACTIVE"
	CardStatusFROZEN    CardStatus = "FROZEN"
	CardStatusCANCELLED CardStatus = "CANCELLED"
)

func (e *CardStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardStatus(s)
	case string:
		*e = CardStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CardStatus: %T", src)
	}
	return nil
}

type NullCardStatus struct {
	CardStatus CardStatus `json:"card_status"`
	Valid      bool       `json:"valid"` // Valid is true if CardStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CardStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardStatus), nil
}

type CardType string

const (
	CardTypeVIRTUAL  CardType = "VIRTUAL"
	CardTypePHYSICAL CardType = "PHYSICAL"
)

func (e *CardType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardType(s)
	case string:
		*e = CardType(s)
	default:
		return fmt.Errorf("unsupported scan type for CardType: %T", src)
	}
	return nil
}

type NullCardType struct {
	CardType CardType `json:"card_type"`
	Valid    bool     `json:"valid"` // Valid is true if CardType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardType) Scan(value interface{}) error {
	if value == nil {
		ns.CardType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardType), nil
}

type CustomerStatus string

const (
	CustomerStatusPENDING   CustomerStatus = "PENDING"
	CustomerStatusACTIVE    CustomerStatus = "ACTIVE"
	CustomerStatusSUSPENDED CustomerStatus = "SUSPENDED"
	CustomerStatusCLOSED    CustomerStatus = "CLOSED"
)

func (e *CustomerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CustomerStatus(s)
	case string:
		*e = CustomerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CustomerStatus: %T", src)
	}
	return nil
}

type NullCustomerStatus struct {
	CustomerStatus CustomerStatus `json:"customer_status"`
	Valid          bool           `json:"valid"` // Valid is true if CustomerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCustomerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CustomerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CustomerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCustomerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CustomerStatus), nil
}

type DiscrepancyStatus string

const (
	DiscrepancyStatusOPEN     DiscrepancyStatus = "OPEN"
	DiscrepancyStatusRESOLVED DiscrepancyStatus = "RESOLVED"
	DiscrepancyStatusIGNORED  DiscrepancyStatus = "IGNORED"
)

func (e *DiscrepancyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscrepancyStatus(s)
	case string:
		*e = DiscrepancyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscrepancyStatus: %T", src)
	}
	return nil
}

type NullDiscrepancyStatus struct {
	DiscrepancyStatus DiscrepancyStatus `json:"discrepancy_status"`
	Valid             bool              `json:"valid"` // Valid is true if DiscrepancyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscrepancyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DiscrepancyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscrepancyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscrepancyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscrepancyStatus), nil
}

type DocumentType string

const (
	DocumentTypePASSPORT       DocumentType = "PASSPORT"
	DocumentTypeDRIVERSLICENSE DocumentType = "DRIVERS_LICENSE"
	DocumentTypeNATIONALID     DocumentType = "NATIONAL_ID"
	DocumentTypeUTILITYBILL    DocumentType = "UTILITY_BILL"
	DocumentTypeBANKSTATEMENT  DocumentType = "BANK_STATEMENT"
)

func (e *DocumentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocumentType(s)
	case string:
		*e = DocumentType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocumentType: %T", src)
	}
	return nil
}

type NullDocumentType struct {
	DocumentType DocumentType `json:"document_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocumentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocumentType) Scan(value interface{}) error {
	if value == nil {
		ns.DocumentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocumentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocumentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocumentType), nil
}

type EntryDirection string

const (
	EntryDirectionDEBIT  EntryDirection = "DEBIT"
	EntryDirectionCREDIT EntryDirection = "CREDIT"
)

func (e *EntryDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryDirection(s)
	case string:
		*e = EntryDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryDirection: %T", src)
	}
	return nil
}

type NullEntryDirection struct {
	EntryDirection EntryDirection `json:"entry_direction"`
	Valid          bool           `json:"valid"` // Valid is true if EntryDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryDirection) Scan(value interface{}) error {
	if value == nil {
		ns.EntryDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryDirection), nil
}

type FeeStatus string

const (
	FeeStatusACTIVE   FeeStatus = "ACTIVE"
	FeeStatusINACTIVE FeeStatus = "INACTIVE"
)

func (e *FeeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeeStatus(s)
	case string:
		*e = FeeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FeeStatus: %T", src)
	}
	return nil
}

type NullFeeStatus struct {
	FeeStatus FeeStatus `json:"fee_status"`
	Valid     bool      `json:"valid"` // Valid is true if FeeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FeeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeeStatus), nil
}

type FeeType string

const (
	FeeTypeFIXED      FeeType = "FIXED"
	FeeTypePERCENTAGE FeeType = "PERCENTAGE"
)

func (e *FeeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FeeType(s)
	case string:
		*e = FeeType(s)
	default:
		return fmt.Errorf("unsupported scan type for FeeType: %T", src)
	}
	return nil
}

type NullFeeType struct {
	FeeType FeeType `json:"fee_type"`
	Valid   bool    `json:"valid"` // Valid is true if FeeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFeeType) Scan(value interface{}) error {
	if value == nil {
		ns.FeeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FeeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFeeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FeeType), nil
}

type FraudRuleAction string

const (
	FraudRuleActionALLOW      FraudRuleAction = "ALLOW"
	FraudRuleActionFLAG       FraudRuleAction = "FLAG"
	FraudRuleActionBLOCK      FraudRuleAction = "BLOCK"
	FraudRuleActionREQUIREMFA FraudRuleAction = "REQUIRE_MFA"
)

func (e *FraudRuleAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FraudRuleAction(s)
	case string:
		*e = FraudRuleAction(s)
	default:
		return fmt.Errorf("unsupported scan type for FraudRuleAction: %T", src)
	}
	return nil
}

type NullFraudRuleAction struct {
	FraudRuleAction FraudRuleAction `json:"fraud_rule_action"`
	Valid           bool            `json:"valid"` // Valid is true if FraudRuleAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFraudRuleAction) Scan(value interface{}) error {
	if value == nil {
		ns.FraudRuleAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FraudRuleAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFraudRuleAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FraudRuleAction), nil
}

type KycTier string

const (
	KycTierTIER0 KycTier = "TIER_0"
	KycTierTIER1 KycTier = "TIER_1"
	KycTierTIER2 KycTier = "TIER_2"
	KycTierTIER3 KycTier = "TIER_3"
)

func (e *KycTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KycTier(s)
	case string:
		*e = KycTier(s)
	default:
		return fmt.Errorf("unsupported scan type for KycTier: %T", src)
	}
	return nil
}

type NullKycTier struct {
	KycTier KycTier `json:"kyc_tier"`
	Valid   bool    `json:"valid"` // Valid is true if KycTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKycTier) Scan(value interface{}) error {
	if value == nil {
		ns.KycTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KycTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKycTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KycTier), nil
}

type NotificationStatus string

const (
	NotificationStatusPENDING NotificationStatus = "PENDING"
	NotificationStatusSENT    NotificationStatus = "SENT"
	NotificationStatusFAILED  NotificationStatus = "FAILED"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type NotificationType string

const (
	NotificationTypeEMAIL NotificationType = "EMAIL"
	NotificationTypeSMS   NotificationType = "SMS"
	NotificationTypePUSH  NotificationType = "PUSH"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING   OutboxStatus = "PENDING"
	OutboxStatusPROCESSED OutboxStatus = "PROCESSED"
	OutboxStatusFAILED    OutboxStatus = "FAILED"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus `json:"outbox_status"`
	Valid        bool         `json:"valid"` // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PayoutMethod string

const (
	PayoutMethodBANKTRANSFER PayoutMethod = "BANK_TRANSFER"
	PayoutMethodMOBILEMONEY  PayoutMethod = "MOBILE_MONEY"
	PayoutMethodCASHPICKUP   PayoutMethod = "CASH_PICKUP"
)

func (e *PayoutMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutMethod(s)
	case string:
		*e = PayoutMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutMethod: %T", src)
	}
	return nil
}

type NullPayoutMethod struct {
	PayoutMethod PayoutMethod `json:"payout_method"`
	Valid        bool         `json:"valid"` // Valid is true if PayoutMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutMethod), nil
}

type PayoutStatus string

const (
	PayoutStatusPENDING    PayoutStatus = "PENDING"
	PayoutStatusPROCESSING PayoutStatus = "PROCESSING"
	PayoutStatusSENT       PayoutStatus = "SENT"
	PayoutStatusCOMPLETED  PayoutStatus = "COMPLETED"
	PayoutStatusFAILED     PayoutStatus = "FAILED"
	PayoutStatusRETURNED   PayoutStatus = "RETURNED"
)

func (e *PayoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutStatus(s)
	case string:
		*e = PayoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutStatus: %T", src)
	}
	return nil
}

type NullPayoutStatus struct {
	PayoutStatus PayoutStatus `json:"payout_status"`
	Valid        bool         `json:"valid"` // Valid is true if PayoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutStatus), nil
}

type ReconciliationStatus string

const (
	ReconciliationStatusRUNNING                    ReconciliationStatus = "RUNNING"
	ReconciliationStatusCOMPLETEDSUCCESS           ReconciliationStatus = "COMPLETED_SUCCESS"
	ReconciliationStatusCOMPLETEDWITHDISCREPANCIES ReconciliationStatus = "COMPLETED_WITH_DISCREPANCIES"
	ReconciliationStatusFAILED                     ReconciliationStatus = "FAILED"
)

func (e *ReconciliationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReconciliationStatus(s)
	case string:
		*e = ReconciliationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReconciliationStatus: %T", src)
	}
	return nil
}

type NullReconciliationStatus struct {
	ReconciliationStatus ReconciliationStatus `json:"reconciliation_status"`
	Valid                bool                 `json:"valid"` // Valid is true if ReconciliationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReconciliationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReconciliationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReconciliationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReconciliationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReconciliationStatus), nil
}

type SagaStatus string

const (
	SagaStatusSTARTED            SagaStatus = "STARTED"
	SagaStatusCOMPLETED          SagaStatus = "COMPLETED"
	SagaStatusABORTED            SagaStatus = "ABORTED"
	SagaStatusCOMPENSATING       SagaStatus = "COMPENSATING"
	SagaStatusCOMPENSATED        SagaStatus = "COMPENSATED"
	SagaStatusFAILEDTOCOMPENSATE SagaStatus = "FAILED_TO_COMPENSATE"
)

func (e *SagaStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SagaStatus(s)
	case string:
		*e = SagaStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SagaStatus: %T", src)
	}
	return nil
}

type NullSagaStatus struct {
	SagaStatus SagaStatus `json:"saga_status"`
	Valid      bool       `json:"valid"` // Valid is true if SagaStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSagaStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SagaStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SagaStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSagaStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SagaStatus), nil
}

type SagaStepStatus string

const (
	SagaStepStatusPENDING     SagaStepStatus = "PENDING"
	SagaStepStatusSTARTED     SagaStepStatus = "STARTED"
	SagaStepStatusCOMPLETED   SagaStepStatus = "COMPLETED"
	SagaStepStatusFAILED      SagaStepStatus = "FAILED"
	SagaStepStatusCOMPENSATED SagaStepStatus = "COMPENSATED"
)

func (e *SagaStepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SagaStepStatus(s)
	case string:
		*e = SagaStepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SagaStepStatus: %T", src)
	}
	return nil
}

type NullSagaStepStatus struct {
	SagaStepStatus SagaStepStatus `json:"saga_step_status"`
	Valid          bool           `json:"valid"` // Valid is true if SagaStepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSagaStepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SagaStepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SagaStepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSagaStepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SagaStepStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusPENDING   TransactionStatus = "PENDING"
	TransactionStatusCOMPLETED TransactionStatus = "COMPLETED"
	TransactionStatusFAILED    TransactionStatus = "FAILED"
	TransactionStatusREVERSED  TransactionStatus = "REVERSED"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type TransactionType string

const (
	TransactionTypeDEPOSIT    TransactionType = "DEPOSIT"
	TransactionTypeWITHDRAWAL TransactionType = "WITHDRAWAL"
	TransactionTypeTRANSFER   TransactionType = "TRANSFER"
	TransactionTypePAYOUT     TransactionType = "PAYOUT"
	TransactionTypeFEE        TransactionType = "FEE"
	TransactionTypeREFUND     TransactionType = "REFUND"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type TransferStatus string

const (
	TransferStatusPENDING    TransferStatus = "PENDING"
	TransferStatusPROCESSING TransferStatus = "PROCESSING"
	TransferStatusCOMPLETED  TransferStatus = "COMPLETED"
	TransferStatusFAILED     TransferStatus = "FAILED"
	TransferStatusREVERSED   TransferStatus = "REVERSED"
)

func (e *TransferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferStatus(s)
	case string:
		*e = TransferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferStatus: %T", src)
	}
	return nil
}

type NullTransferStatus struct {
	TransferStatus TransferStatus `json:"transfer_status"`
	Valid          bool           `json:"valid"` // Valid is true if TransferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferStatus), nil
}

type VerificationStatus string

const (
	VerificationStatusPENDING  VerificationStatus = "PENDING"
	VerificationStatusAPPROVED VerificationStatus = "APPROVED"
	VerificationStatusREJECTED VerificationStatus = "REJECTED"
	VerificationStatusEXPIRED  VerificationStatus = "EXPIRED"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type WalletStatus string

const (
	WalletStatusACTIVE WalletStatus = "ACTIVE"
	WalletStatusLOCKED WalletStatus = "LOCKED"
	WalletStatusCLOSED WalletStatus = "CLOSED"
)

func (e *WalletStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletStatus(s)
	case string:
		*e = WalletStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletStatus: %T", src)
	}
	return nil
}

type NullWalletStatus struct {
	WalletStatus WalletStatus `json:"wallet_status"`
	Valid        bool         `json:"valid"` // Valid is true if WalletStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WalletStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletStatus), nil
}

type WebhookDeliveryStatus string

const (
	WebhookDeliveryStatusPENDING WebhookDeliveryStatus = "PENDING"
	WebhookDeliveryStatusSUCCESS WebhookDeliveryStatus = "SUCCESS"
	WebhookDeliveryStatusFAILED  WebhookDeliveryStatus = "FAILED"
	WebhookDeliveryStatusRETRIED WebhookDeliveryStatus = "RETRIED"
)

func (e *WebhookDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookDeliveryStatus(s)
	case string:
		*e = WebhookDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookDeliveryStatus: %T", src)
	}
	return nil
}

type NullWebhookDeliveryStatus struct {
	WebhookDeliveryStatus WebhookDeliveryStatus `json:"webhook_delivery_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if WebhookDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookDeliveryStatus), nil
}

type WebhookStatus string

const (
	WebhookStatusACTIVE   WebhookStatus = "ACTIVE"
	WebhookStatusINACTIVE WebhookStatus = "INACTIVE"
)

func (e *WebhookStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookStatus(s)
	case string:
		*e = WebhookStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookStatus: %T", src)
	}
	return nil
}

type NullWebhookStatus struct {
	WebhookStatus WebhookStatus `json:"webhook_status"`
	Valid         bool          `json:"valid"` // Valid is true if WebhookStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookStatus), nil
}

type Account struct {
	ID            uuid.UUID     `json:"id"`
	CustomerID    uuid.NullUUID `json:"customer_id"`
	AccountNumber string        `json:"account_number"`
	Type          AccountType   `json:"type"`
	Status        AccountStatus `json:"status"`
	Currency      string        `json:"currency"`
	Balance       int64         `json:"balance"`
	HoldBalance   int64         `json:"hold_balance"`
	Version       int64         `json:"version"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type ApiKey struct {
	ID         uuid.UUID      `json:"id"`
	CustomerID uuid.UUID      `json:"customer_id"`
	KeyHash    string         `json:"key_hash"`
	Prefix     string         `json:"prefix"`
	Name       sql.NullString `json:"name"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	IsRevoked  bool           `json:"is_revoked"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Beneficiary struct {
	ID            uuid.UUID             `json:"id"`
	CustomerID    uuid.UUID             `json:"customer_id"`
	Name          string                `json:"name"`
	Type          PayoutMethod          `json:"type"`
	AccountNumber sql.NullString        `json:"account_number"`
	BankCode      sql.NullString        `json:"bank_code"`
	RoutingNumber sql.NullString        `json:"routing_number"`
	SwiftBic      sql.NullString        `json:"swift_bic"`
	Currency      string                `json:"currency"`
	Status        BeneficiaryStatus     `json:"status"`
	Metadata      pqtype.NullRawMessage `json:"metadata"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

type Card struct {
	ID            uuid.UUID      `json:"id"`
	CustomerID    uuid.UUID      `json:"customer_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Type          CardType       `json:"type"`
	Status        CardStatus     `json:"status"`
	LastFour      string         `json:"last_four"`
	ExpiryMonth   int32          `json:"expiry_month"`
	ExpiryYear    int32          `json:"expiry_year"`
	Token         sql.NullString `json:"token"`
	ProviderID    sql.NullString `json:"provider_id"`
	SpendingLimit sql.NullInt64  `json:"spending_limit"`
	DailyLimit    sql.NullInt64  `json:"daily_limit"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type Customer struct {
	ID          uuid.UUID             `json:"id"`
	Email       string                `json:"email"`
	PhoneNumber sql.NullString        `json:"phone_number"`
	FirstName   string                `json:"first_name"`
	LastName    string                `json:"last_name"`
	DateOfBirth sql.NullTime          `json:"date_of_birth"`
	Status      CustomerStatus        `json:"status"`
	KycLevel    KycTier               `json:"kyc_level"`
	CountryCode string                `json:"country_code"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type Fee struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	ScheduleID    uuid.NullUUID  `json:"schedule_id"`
	Amount        int64          `json:"amount"`
	Currency      string         `json:"currency"`
	Description   sql.NullString `json:"description"`
	CreatedAt     time.Time      `json:"created_at"`
}

type FeeSchedule struct {
	ID              uuid.UUID       `json:"id"`
	TransactionType TransactionType `json:"transaction_type"`
	FeeType         FeeType         `json:"fee_type"`
	Amount          int64           `json:"amount"`
	Currency        sql.NullString  `json:"currency"`
	Status          FeeStatus       `json:"status"`
	ValidFrom       time.Time       `json:"valid_from"`
	ValidUntil      sql.NullTime    `json:"valid_until"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type FraudAlert struct {
	ID            uuid.UUID             `json:"id"`
	CustomerID    uuid.NullUUID         `json:"customer_id"`
	TransactionID uuid.NullUUID         `json:"transaction_id"`
	RuleID        uuid.NullUUID         `json:"rule_id"`
	Score         int32                 `json:"score"`
	Status        AlertStatus           `json:"status"`
	Details       pqtype.NullRawMessage `json:"details"`
	ResolvedBy    uuid.NullUUID         `json:"resolved_by"`
	ResolvedAt    sql.NullTime          `json:"resolved_at"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

type FraudRule struct {
	ID                  uuid.UUID       `json:"id"`
	Name                string          `json:"name"`
	Description         sql.NullString  `json:"description"`
	ConditionExpression string          `json:"condition_expression"`
	Action              FraudRuleAction `json:"action"`
	IsActive            bool            `json:"is_active"`
	CreatedAt           time.Time       `json:"created_at"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

type IdempotencyKey struct {
	ID            uuid.UUID             `json:"id"`
	Key           string                `json:"key"`
	CustomerID    uuid.UUID             `json:"customer_id"`
	RequestPath   string                `json:"request_path"`
	RequestMethod string                `json:"request_method"`
	RequestParams json.RawMessage       `json:"request_params"`
	ResponseCode  sql.NullInt32         `json:"response_code"`
	ResponseBody  pqtype.NullRawMessage `json:"response_body"`
	LockedAt      sql.NullTime          `json:"locked_at"`
	CreatedAt     time.Time             `json:"created_at"`
	UpdatedAt     time.Time             `json:"updated_at"`
}

type KycDocument struct {
	ID             uuid.UUID          `json:"id"`
	CustomerID     uuid.UUID          `json:"customer_id"`
	Type           DocumentType       `json:"type"`
	DocumentUrl    string             `json:"document_url"`
	CountryOfIssue sql.NullString     `json:"country_of_issue"`
	IssuedDate     sql.NullTime       `json:"issued_date"`
	ExpiryDate     sql.NullTime       `json:"expiry_date"`
	Status         VerificationStatus `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type KycVerification struct {
	ID                uuid.UUID             `json:"id"`
	CustomerID        uuid.UUID             `json:"customer_id"`
	Provider          sql.NullString        `json:"provider"`
	ProviderReference sql.NullString        `json:"provider_reference"`
	Status            VerificationStatus    `json:"status"`
	Reason            sql.NullString        `json:"reason"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type LedgerEntry struct {
	ID            uuid.UUID      `json:"id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	AccountID     uuid.UUID      `json:"account_id"`
	Amount        int64          `json:"amount"`
	Currency      string         `json:"currency"`
	Direction     EntryDirection `json:"direction"`
	Description   sql.NullString `json:"description"`
	ReferenceID   sql.NullString `json:"reference_id"`
	CreatedAt     time.Time      `json:"created_at"`
}

type NotificationQueue struct {
	ID           uuid.UUID          `json:"id"`
	CustomerID   uuid.NullUUID      `json:"customer_id"`
	Type         NotificationType   `json:"type"`
	Recipient    string             `json:"recipient"`
	TemplateID   uuid.NullUUID      `json:"template_id"`
	Subject      sql.NullString     `json:"subject"`
	Body         string             `json:"body"`
	Status       NotificationStatus `json:"status"`
	RetryCount   int32              `json:"retry_count"`
	NextRetryAt  sql.NullTime       `json:"next_retry_at"`
	ErrorMessage sql.NullString     `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type NotificationTemplate struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Type      NotificationType `json:"type"`
	Subject   sql.NullString   `json:"subject"`
	Body      string           `json:"body"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
}

type OutboxEvent struct {
	ID            uuid.UUID       `json:"id"`
	AggregateType string          `json:"aggregate_type"`
	AggregateID   string          `json:"aggregate_id"`
	EventType     string          `json:"event_type"`
	Payload       json.RawMessage `json:"payload"`
	Status        OutboxStatus    `json:"status"`
	Error         sql.NullString  `json:"error"`
	RetryCount    int32           `json:"retry_count"`
	CreatedAt     time.Time       `json:"created_at"`
	ProcessedAt   sql.NullTime    `json:"processed_at"`
}

type Payout struct {
	ID                uuid.UUID             `json:"id"`
	TransactionID     uuid.NullUUID         `json:"transaction_id"`
	SourceAccountID   uuid.UUID             `json:"source_account_id"`
	BeneficiaryID     uuid.UUID             `json:"beneficiary_id"`
	Amount            int64                 `json:"amount"`
	Currency          string                `json:"currency"`
	ProviderID        sql.NullString        `json:"provider_id"`
	ProviderReference sql.NullString        `json:"provider_reference"`
	Status            PayoutStatus          `json:"status"`
	Method            PayoutMethod          `json:"method"`
	FeeAmount         int64                 `json:"fee_amount"`
	Metadata          pqtype.NullRawMessage `json:"metadata"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type ReconciliationDiscrepancy struct {
	ID                uuid.UUID         `json:"id"`
	RunID             uuid.UUID         `json:"run_id"`
	TransactionID     uuid.NullUUID     `json:"transaction_id"`
	ProviderReference sql.NullString    `json:"provider_reference"`
	Type              string            `json:"type"`
	InternalAmount    sql.NullInt64     `json:"internal_amount"`
	ProviderAmount    sql.NullInt64     `json:"provider_amount"`
	Currency          sql.NullString    `json:"currency"`
	Status            DiscrepancyStatus `json:"status"`
	ResolutionNotes   sql.NullString    `json:"resolution_notes"`
	CreatedAt         time.Time         `json:"created_at"`
	UpdatedAt         time.Time         `json:"updated_at"`
}

type ReconciliationRun struct {
	ID                    uuid.UUID            `json:"id"`
	ProviderID            string               `json:"provider_id"`
	RunDate               time.Time            `json:"run_date"`
	Status                ReconciliationStatus `json:"status"`
	TotalRecordsProcessed int32                `json:"total_records_processed"`
	TotalDiscrepancies    int32                `json:"total_discrepancies"`
	StartedAt             time.Time            `json:"started_at"`
	CompletedAt           sql.NullTime         `json:"completed_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	IsRevoked bool      `json:"is_revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Saga struct {
	ID          uuid.UUID       `json:"id"`
	SagaType    string          `json:"saga_type"`
	Status      SagaStatus      `json:"status"`
	Payload     json.RawMessage `json:"payload"`
	CurrentStep int32           `json:"current_step"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type SagaStep struct {
	ID          uuid.UUID      `json:"id"`
	SagaID      uuid.UUID      `json:"saga_id"`
	StepName    string         `json:"step_name"`
	StepOrder   int32          `json:"step_order"`
	Status      SagaStepStatus `json:"status"`
	Error       sql.NullString `json:"error"`
	StartedAt   sql.NullTime   `json:"started_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Transaction struct {
	ID          uuid.UUID             `json:"id"`
	Type        TransactionType       `json:"type"`
	Status      TransactionStatus     `json:"status"`
	Amount      int64                 `json:"amount"`
	Currency    string                `json:"currency"`
	ReferenceID sql.NullString        `json:"reference_id"`
	Metadata    pqtype.NullRawMessage `json:"metadata"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type Transfer struct {
	ID                   uuid.UUID      `json:"id"`
	TransactionID        uuid.NullUUID  `json:"transaction_id"`
	SourceAccountID      uuid.UUID      `json:"source_account_id"`
	DestinationAccountID uuid.UUID      `json:"destination_account_id"`
	Amount               int64          `json:"amount"`
	Currency             string         `json:"currency"`
	Status               TransferStatus `json:"status"`
	FeeAmount            int64          `json:"fee_amount"`
	Description          sql.NullString `json:"description"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID      `json:"id"`
	CustomerID          uuid.NullUUID  `json:"customer_id"`
	Email               string         `json:"email"`
	PasswordHash        string         `json:"password_hash"`
	MfaSecret           sql.NullString `json:"mfa_secret"`
	MfaEnabled          bool           `json:"mfa_enabled"`
	IsLocked            bool           `json:"is_locked"`
	FailedLoginAttempts int32          `json:"failed_login_attempts"`
	LastLoginAt         sql.NullTime   `json:"last_login_at"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type Wallet struct {
	ID               uuid.UUID             `json:"id"`
	CustomerID       uuid.UUID             `json:"customer_id"`
	WalletAddress    string                `json:"wallet_address"`
	Currency         string                `json:"currency"`
	Status           WalletStatus          `json:"status"`
	AvailableBalance int64                 `json:"available_balance"`
	LockedBalance    int64                 `json:"locked_balance"`
	Version          int64                 `json:"version"`
	Metadata         pqtype.NullRawMessage `json:"metadata"`
	CreatedAt        time.Time             `json:"created_at"`
	UpdatedAt        time.Time             `json:"updated_at"`
}

type Webhook struct {
	ID         uuid.UUID     `json:"id"`
	CustomerID uuid.UUID     `json:"customer_id"`
	Url        string        `json:"url"`
	Secret     string        `json:"secret"`
	Events     []string      `json:"events"`
	Status     WebhookStatus `json:"status"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID             `json:"id"`
	WebhookID    uuid.UUID             `json:"webhook_id"`
	EventType    string                `json:"event_type"`
	Payload      json.RawMessage       `json:"payload"`
	Status       WebhookDeliveryStatus `json:"status"`
	StatusCode   sql.NullInt32         `json:"status_code"`
	ResponseBody sql.NullString        `json:"response_body"`
	RetryCount   int32                 `json:"retry_count"`
	NextRetryAt  sql.NullTime          `json:"next_retry_at"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
}
