// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_gen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	GetCustomerByEmail(ctx context.Context, email string) (Customer, error)
	GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error)
	UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
