// topics_list.dart

const List<String> topics = [
  'Maps Integration',
  'Payment Systems',
  'Push Notifications',
  'Background Services',
  'User Security',
  'Real-Time Communication (RTC)',
  'State Management',
  'Local Database (SQLite)',
  'Authentication & Authorization',
  'API Integration & RESTful Services',
  'Animations & Transitions',
  'File Upload & Download',
  'Multithreading & Isolates',
  'Camera Integration',
  'Media Handling (Audio/Video)',
  '(Shared Preferences & Secure Storage)',
  'Deep Linking',
  'Internationalization & Localization',
  'Device Sensors (Accelerometer, Gyroscope)',
  'App Performance Optimization',
  'Testing (Unit, Widget, Integration)',
  'App Distribution (Play Store, App Store)',
  'Version Control (Git & CI/CD)',
  'Responsive UI & Screen Adaptations',
  'App Security Best Practices',
];
